TrajectoryPlannerROS:
  # 機器人配置參數
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.2
  
  # 加速度限制
  acc_lim_x: 0.5
  acc_lim_theta: 1.0
  
  # 容差
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  
  # 前向模擬參數
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20
  
  # 軌跡評分
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  
  # 其他
  dwa: true
  holonomic_robot: false
  meter_scoring: true
