<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="robot_sensors" params="parent">
    
    <!-- 雷射掃描器 -->
    <link name="laser_link">
      <visual>
        <geometry>
          <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="red"/>
      </visual>
      
      <collision>
        <geometry>
          <cylinder radius="0.05" length="0.04"/>
        </geometry>
      </collision>
      
      <xacro:cylinder_inertia m="0.1" r="0.05" h="0.04"/>
    </link>
    
    <joint name="laser_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="laser_link"/>
      <origin xyz="${base_length/2 - 0.05} 0 ${base_height/2 + 0.02}" rpy="0 0 0"/>
    </joint>
    
    <!-- 相機（選擇性，用於桌號識別） -->
    <link name="camera_link">
      <visual>
        <geometry>
          <box size="0.03 0.06 0.03"/>
        </geometry>
        <material name="black"/>
      </visual>
      
      <collision>
        <geometry>
          <box size="0.03 0.06 0.03"/>
        </geometry>
      </collision>
      
      <xacro:box_inertia m="0.05" w="0.03" h="0.06" d="0.03"/>
    </link>
    
    <joint name="camera_joint" type="fixed">
      <parent link="tray_support"/>
      <child link="camera_link"/>
      <origin xyz="0.1 0 ${tray_height/2}" rpy="0 0 0"/>
    </joint>
    
  </xacro:macro>

</robot>
